### ISSUE TITLE
Use `Waker::will_wake()`

### ISSUE THREAD

**Issue by daxpedda** [smol-rs/atomic-waker#11]
I was wondering if there is any interest in adding this optimization, basically avoiding cloning the `Waker` if it isn't necessary.

Happy to make a PR.

**Comment by notgull** [comment]
Looking through the history of the original `AtomicWaker` implementation, it looks like [it originally had a test like this](https://github.com/rust-lang/futures-rs/blob/cc6bfd6845df4aab64a9cb970df6a5b3d3791cc3/src/task_impl2/atomic_task.rs#L55-L60), but it was [removed later on](https://github.com/rust-lang/futures-rs/blob/42f690993549791dece4c81e2ff33d3056fccedf/src/task_impl/atomic_task.rs#L55-L60). 

I'm not familiar with `futures`' internals, but from a brief glance you could probably just add the check [here](https://github.com/smol-rs/atomic-waker/blob/b96ee39889ab92bd736ffc10933c81a745a291a6/src/lib.rs#L287-L288).
